"""
Party Run-of-Show — block library + occasion templates.

Each block has a 5-level energy tag (1=warm/wind-down, 5=peak chaos)
and stage tag (welcome / opener / main / intermission / closer / wind_down).
"""

# Energy levels (used for arc enforcement + scoring)
ENERGY_WARM = 1
ENERGY_LOW = 2
ENERGY_MID = 3
ENERGY_HIGH = 4
ENERGY_PEAK = 5


BLOCKS = [
    # ---------- WELCOME ----------
    {
        "id": "welcome_drink_station",
        "stage": "welcome",
        "title": "Drink station self-serve",
        "energy": ENERGY_WARM,
        "default_minutes": 15,
        "materials": ["drinks", "ice", "cups", "napkins", "opener"],
        "min_group": 2, "max_group": 50,
        "ages": "adults_teens",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["birthday", "game_night", "dinner_party", "holiday", "reunion", "couples_night", "work_offsite"],
        "rationale": "Self-serve station lets guests arrive at different paces and breaks the standing-around-awkwardly feeling.",
    },
    {
        "id": "welcome_passes_around",
        "stage": "welcome",
        "title": "Name + one-word pass-around",
        "energy": ENERGY_WARM,
        "default_minutes": 10,
        "materials": [],
        "min_group": 3, "max_group": 20,
        "ages": "adults_teens",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["birthday", "reunion", "work_offsite"],
        "rationale": "Tiny intro ritual: name + one word for how you're feeling. Beats pure small talk for groups that don't all know each other.",
    },
    {
        "id": "welcome_welcome_sign",
        "stage": "welcome",
        "title": "Welcome sign + photo wall",
        "energy": ENERGY_WARM,
        "default_minutes": 10,
        "materials": ["chalkboard/paper", "props", "polaroid/phone camera"],
        "min_group": 4, "max_group": 50,
        "ages": "all",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["birthday", "holiday", "reunion", "kids_party"],
        "rationale": "Photo-op wall turns early arrivals into a focal point. Doubles as a take-home for the host.",
    },
    {
        "id": "welcome_kids_craft",
        "stage": "welcome",
        "title": "Welcome craft table (kids)",
        "energy": ENERGY_LOW,
        "default_minutes": 20,
        "materials": ["markers", "stickers", "construction paper", "table"],
        "min_group": 4, "max_group": 25,
        "ages": "kids",
        "noise": "mid",
        "conflict_safe": True,
        "occasions": ["kids_party", "birthday"],
        "rationale": "Buys parents 20 quiet minutes while latecomers arrive.",
    },

    # ---------- OPENER ----------
    {
        "id": "opener_two_truths",
        "stage": "opener",
        "title": "Two truths and a lie (round-robin)",
        "energy": ENERGY_LOW,
        "default_minutes": 20,
        "materials": [],
        "min_group": 4, "max_group": 12,
        "ages": "adults_teens",
        "noise": "mid",
        "conflict_safe": True,
        "occasions": ["birthday", "game_night", "reunion", "work_offsite"],
        "rationale": "Classic icebreaker. Round-robin format keeps quiet guests in the rotation.",
    },
    {
        "id": "opener_never_have_i",
        "stage": "opener",
        "title": "Never-have-I-ever (light version)",
        "energy": ENERGY_MID,
        "default_minutes": 20,
        "materials": [],
        "min_group": 4, "max_group": 15,
        "ages": "adults_teens",
        "noise": "mid",
        "conflict_safe": False,
        "occasions": ["birthday", "game_night", "couples_night"],
        "rationale": "Light, funny, escalates gently. Skip with coworkers or inlaws unless you trust the group.",
    },
    {
        "id": "opener_team_caption",
        "stage": "opener",
        "title": "Caption-this photo round",
        "energy": ENERGY_LOW,
        "default_minutes": 15,
        "materials": ["printed weird photos", "pens"],
        "min_group": 3, "max_group": 20,
        "ages": "adults_teens",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["work_offsite", "reunion", "dinner_party"],
        "rationale": "Quiet small-group writing then share-aloud — safer than round-robin storytelling.",
    },
    {
        "id": "opener_kids_parade",
        "stage": "opener",
        "title": "Decorate-your-name-tag parade",
        "energy": ENERGY_LOW,
        "default_minutes": 15,
        "materials": ["name tags", "markers", "stickers"],
        "min_group": 3, "max_group": 25,
        "ages": "kids",
        "noise": "mid",
        "conflict_safe": True,
        "occasions": ["kids_party", "birthday"],
        "rationale": "Settled-in activity that doubles as a name-learning ritual.",
    },

    # ---------- MAIN ----------
    {
        "id": "main_trivia_rounds",
        "stage": "main",
        "title": "Trivia — 3 themed rounds",
        "energy": ENERGY_MID,
        "default_minutes": 45,
        "materials": ["questions printed", "score sheet", "pens"],
        "min_group": 4, "max_group": 30,
        "ages": "adults_teens",
        "noise": "mid",
        "conflict_safe": True,
        "occasions": ["birthday", "game_night", "holiday", "work_offsite"],
        "rationale": "Universal team activity. 3 rounds keeps the energy from collapsing on a single category.",
    },
    {
        "id": "main_charades",
        "stage": "main",
        "title": "Charades (team-based)",
        "energy": ENERGY_HIGH,
        "default_minutes": 30,
        "materials": ["slips of paper in a bowl"],
        "min_group": 4, "max_group": 20,
        "ages": "all",
        "noise": "high",
        "conflict_safe": True,
        "occasions": ["birthday", "game_night", "reunion", "kids_party"],
        "rationale": "High-energy, language-free, instant laughs. Steer clear of personal-phrase charades.",
    },
    {
        "id": "main_pictionary",
        "stage": "main",
        "title": "Pictionary relay",
        "energy": ENERGY_HIGH,
        "default_minutes": 30,
        "materials": ["whiteboard/pad", "markers", "timer"],
        "min_group": 4, "max_group": 16,
        "ages": "all",
        "noise": "high",
        "conflict_safe": True,
        "occasions": ["birthday", "game_night", "work_offsite"],
        "rationale": "Drawing-only rule = everyone can play. Relay format gives quieter players a shorter turn.",
    },
    {
        "id": "main_codenames",
        "stage": "main",
        "title": "Codenames tournament",
        "energy": ENERGY_MID,
        "default_minutes": 45,
        "materials": ["Codenames cards", "two-team colors"],
        "min_group": 4, "max_group": 12,
        "ages": "adults_teens",
        "noise": "mid",
        "conflict_safe": True,
        "occasions": ["game_night", "birthday", "couples_night"],
        "rationale": "Best 2-team associative game for mixed-experience groups.",
    },
    {
        "id": "main_wavelength",
        "stage": "main",
        "title": "Wavelength — 4-round match",
        "energy": ENERGY_MID,
        "default_minutes": 30,
        "materials": ["Wavelength dial + cards"],
        "min_group": 4, "max_group": 12,
        "ages": "adults_teens",
        "noise": "mid",
        "conflict_safe": False,
        "occasions": ["game_night", "couples_night"],
        "rationale": "Reveals how groups think. Skip with brand-new coworkers — it surfaces disagreements fast.",
    },
    {
        "id": "main_karaoke_rounds",
        "stage": "main",
        "title": "Karaoke — 2 rounds, themed",
        "energy": ENERGY_PEAK,
        "default_minutes": 45,
        "materials": ["karaoke app/youtube", "mic", "screen"],
        "min_group": 3, "max_group": 30,
        "ages": "adults_teens",
        "noise": "high",
        "conflict_safe": False,
        "occasions": ["birthday", "holiday", "couples_night"],
        "rationale": "Peak-energy release. Themed rounds (90s / Disney / duets) keeps the floor rotating.",
    },
    {
        "id": "main_pinata",
        "stage": "main",
        "title": "Piñata round",
        "energy": ENERGY_PEAK,
        "default_minutes": 15,
        "materials": ["piñata", "bat", "candy"],
        "min_group": 4, "max_group": 25,
        "ages": "kids",
        "noise": "high",
        "conflict_safe": True,
        "occasions": ["kids_party", "birthday"],
        "rationale": "The single biggest energy spike a kid party gets. Time it before cake.",
    },
    {
        "id": "main_dinner_main",
        "stage": "main",
        "title": "Sit-down dinner service",
        "energy": ENERGY_LOW,
        "default_minutes": 60,
        "materials": ["dinner", "drinks", "music"],
        "min_group": 2, "max_group": 16,
        "ages": "adults_teens",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["dinner_party", "holiday", "reunion", "couples_night"],
        "rationale": "Anchor of any sit-down evening. Plan conversational safety around seating if mixed company.",
    },
    {
        "id": "main_kids_obstacle",
        "stage": "main",
        "title": "Indoor obstacle / scavenger hunt",
        "energy": ENERGY_HIGH,
        "default_minutes": 30,
        "materials": ["printed clues", "props"],
        "min_group": 4, "max_group": 25,
        "ages": "kids",
        "noise": "high",
        "conflict_safe": True,
        "occasions": ["kids_party", "birthday"],
        "rationale": "Channels kid energy into motion. Burns off the sugar spike before cake.",
    },

    # ---------- INTERMISSION ----------
    {
        "id": "intermission_dessert",
        "stage": "intermission",
        "title": "Dessert + coffee bar",
        "energy": ENERGY_LOW,
        "default_minutes": 20,
        "materials": ["dessert", "coffee", "plates"],
        "min_group": 2, "max_group": 50,
        "ages": "all",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["birthday", "dinner_party", "holiday", "reunion", "couples_night", "work_offsite"],
        "rationale": "Natural energy dip. Sugar + caffeine reset before the closing block.",
    },
    {
        "id": "intermission_kids_movie",
        "stage": "intermission",
        "title": "Short film / cartoon intermission",
        "energy": ENERGY_LOW,
        "default_minutes": 20,
        "materials": ["screen", "blankets"],
        "min_group": 3, "max_group": 30,
        "ages": "kids",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["kids_party", "birthday"],
        "rationale": "Calm-down window. 20-min cap so they don't fully zone out before cake.",
    },
    {
        "id": "intermission_walk",
        "stage": "intermission",
        "title": "Group walk around the block",
        "energy": ENERGY_MID,
        "default_minutes": 20,
        "materials": [],
        "min_group": 3, "max_group": 25,
        "ages": "adults_teens",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["dinner_party", "holiday", "couples_night", "reunion"],
        "rationale": "Movement + fresh air breaks heavy-meal torpor. Doubles as 1:1 catch-up time.",
    },
    {
        "id": "intermission_karaoke_lull",
        "stage": "intermission",
        "title": "Quiet music + recharge lull",
        "energy": ENERGY_WARM,
        "default_minutes": 15,
        "materials": ["speaker", "playlist"],
        "min_group": 2, "max_group": 50,
        "ages": "adults_teens",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["birthday", "holiday", "dinner_party"],
        "rationale": "Soundtrack only — no activity. Lets guests choose their next conversation.",
    },

    # ---------- CLOSER ----------
    {
        "id": "closer_toast",
        "stage": "closer",
        "title": "Toast to the guest of honor",
        "energy": ENERGY_MID,
        "default_minutes": 10,
        "materials": ["drinks", "optional speech notes"],
        "min_group": 3, "max_group": 50,
        "ages": "adults_teens",
        "noise": "mid",
        "conflict_safe": True,
        "occasions": ["birthday", "holiday", "reunion", "work_offsite"],
        "rationale": "A toast lands best when everyone is tired enough to listen.",
    },
    {
        "id": "closer_group_photo",
        "stage": "closer",
        "title": "Group photo + candids",
        "energy": ENERGY_LOW,
        "default_minutes": 10,
        "materials": ["phone/tripod"],
        "min_group": 3, "max_group": 50,
        "ages": "all",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["birthday", "holiday", "reunion", "kids_party"],
        "rationale": "Schedule at the energy dip — nobody wanders off, everyone is still dressed.",
    },
    {
        "id": "closer_cake_candles",
        "stage": "closer",
        "title": "Cake + candles + singing",
        "energy": ENERGY_HIGH,
        "default_minutes": 15,
        "materials": ["cake", "candles", "matches/lighter"],
        "min_group": 3, "max_group": 50,
        "ages": "all",
        "noise": "high",
        "conflict_safe": True,
        "occasions": ["birthday", "kids_party"],
        "rationale": "The peak emotional moment — needs to land right before wind-down.",
    },
    {
        "id": "closer_gift_open",
        "stage": "closer",
        "title": "Gift opening round",
        "energy": ENERGY_MID,
        "default_minutes": 20,
        "materials": ["gifts", "scratch paper for thank-you list"],
        "min_group": 3, "max_group": 30,
        "ages": "all",
        "noise": "mid",
        "conflict_safe": False,
        "occasions": ["birthday", "holiday", "reunion", "kids_party"],
        "rationale": "Slip into a calmer spot of the night. Skip if gifts are uneven and feelings could get hurt.",
    },

    # ---------- WIND DOWN ----------
    {
        "id": "wind_down_drink_left",
        "stage": "wind_down",
        "title": "Last-call pour + leftovers",
        "energy": ENERGY_WARM,
        "default_minutes": 15,
        "materials": ["leftover food", "drinks"],
        "min_group": 2, "max_group": 30,
        "ages": "adults_teens",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["dinner_party", "birthday", "holiday", "couples_night"],
        "rationale": "Soft exit signal — guests know it's the home stretch.",
    },
    {
        "id": "wind_down_kids_goodie",
        "stage": "wind_down",
        "title": "Goodie bags + pickup",
        "energy": ENERGY_LOW,
        "default_minutes": 15,
        "materials": ["goodie bags pre-packed"],
        "min_group": 3, "max_group": 25,
        "ages": "kids",
        "noise": "mid",
        "conflict_safe": True,
        "occasions": ["kids_party", "birthday"],
        "rationale": "Bags-at-the-door trick to avoid the 30-min goodbye swirl.",
    },
    {
        "id": "wind_down_chat_cluster",
        "stage": "wind_down",
        "title": "Small-cluster chat + playlist",
        "energy": ENERGY_WARM,
        "default_minutes": 25,
        "materials": ["speaker", "playlist", "comfortable seating"],
        "min_group": 4, "max_group": 16,
        "ages": "adults_teens",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["dinner_party", "couples_night", "reunion"],
        "rationale": "After structured activity, guests re-cluster organically. Let the music do the work.",
    },
    {
        "id": "wind_down_thank_you_notes",
        "stage": "wind_down",
        "title": "Thank-you card station",
        "energy": ENERGY_LOW,
        "default_minutes": 15,
        "materials": ["cards", "pens", "stamps"],
        "min_group": 2, "max_group": 30,
        "ages": "kids",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["kids_party", "birthday", "holiday"],
        "rationale": "Stop the card-writing procrastination at the door.",
    },
    {
        "id": "wind_down_after_dance",
        "stage": "wind_down",
        "title": "Slow-song wind-down dance",
        "energy": ENERGY_LOW,
        "default_minutes": 15,
        "materials": ["playlist", "lights down"],
        "min_group": 4, "max_group": 40,
        "ages": "adults_teens",
        "noise": "mid",
        "conflict_safe": True,
        "occasions": ["wedding_adjacent", "holiday", "reunion"],
        "rationale": "Smooth gear-shift before people peel off.",
    },
    {
        "id": "wind_down_farewell_loop",
        "stage": "wind_down",
        "title": "Farewell loop (10-min cap)",
        "energy": ENERGY_WARM,
        "default_minutes": 10,
        "materials": [],
        "min_group": 2, "max_group": 30,
        "ages": "all",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["dinner_party", "holiday", "reunion", "work_offsite"],
        "rationale": "Hosts set a clear 10-min goodbye window to prevent the long lingering exit.",
    },
    {
        "id": "wind_down_game_afterparty",
        "stage": "wind_down",
        "title": "Light post-game wind-down chat",
        "energy": ENERGY_LOW,
        "default_minutes": 20,
        "materials": ["music", "comfortable seating"],
        "min_group": 3, "max_group": 16,
        "ages": "adults_teens",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["game_night"],
        "rationale": "After structured competition, guests rehash the night's funniest moments — a soft exit after the final round.",
    },
    {
        "id": "wind_down_snack_pack",
        "stage": "wind_down",
        "title": "Snacks + leftovers + recap",
        "energy": ENERGY_WARM,
        "default_minutes": 15,
        "materials": ["leftover snacks", "drinks", "take-home containers"],
        "min_group": 3, "max_group": 30,
        "ages": "adults_teens",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["game_night", "birthday", "holiday", "reunion", "work_offsite"],
        "rationale": "Last-call food + recap conversation. Doubles as a clear signal the night is wrapping.",
    },
    {
        "id": "wind_down_offsite_debrief",
        "stage": "wind_down",
        "title": "Offsite 5-min debrief + goodnights",
        "energy": ENERGY_WARM,
        "default_minutes": 10,
        "materials": ["notepad for one takeaway per person"],
        "min_group": 4, "max_group": 25,
        "ages": "adults_teens",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["work_offsite"],
        "rationale": "Round-the-room one-sentence takeaway. Anchors the offsite with a shared close.",
    },
    {
        "id": "wind_down_couples_last_glass",
        "stage": "wind_down",
        "title": "Last-glass on the porch",
        "energy": ENERGY_WARM,
        "default_minutes": 20,
        "materials": ["drinks", "optional blanket"],
        "min_group": 2, "max_group": 8,
        "ages": "adults_teens",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["couples_night"],
        "rationale": "Two or more couples close out the night with a quiet glass and 1:1 conversation.",
    },
    {
        "id": "wind_down_reunion_signoff",
        "stage": "wind_down",
        "title": "Group selfie + next-date signoff",
        "energy": ENERGY_LOW,
        "default_minutes": 10,
        "materials": ["phone", "shared calendar invite draft"],
        "min_group": 3, "max_group": 25,
        "ages": "adults_teens",
        "noise": "low",
        "conflict_safe": True,
        "occasions": ["reunion"],
        "rationale": "Capture the group + lock the next reunion date while everyone is still there.",
    },
]


OCCASION_TEMPLATES = {
    "birthday": {
        "label": "Birthday (adults)",
        "ages": "adults_teens",
        "default_minutes": 180,
        "default_group_size": 12,
        "default_energy_target": "mid",
        "must_include_stages": ["welcome", "opener", "main", "intermission", "closer", "wind_down"],
        "required_block_ids": ["closer_toast"],  # toast is required for birthdays
        "forbidden_block_ids": ["main_dinner_main"],
    },
    "game_night": {
        "label": "Game night",
        "ages": "adults_teens",
        "default_minutes": 180,
        "default_group_size": 8,
        "default_energy_target": "mid",
        "must_include_stages": ["welcome", "opener", "main", "wind_down"],
        "required_block_ids": [],
        "forbidden_block_ids": ["main_dinner_main", "main_pinata"],
    },
    "dinner_party": {
        "label": "Dinner party",
        "ages": "adults_teens",
        "default_minutes": 180,
        "default_group_size": 8,
        "default_energy_target": "low",
        "must_include_stages": ["welcome", "main", "wind_down"],
        "required_block_ids": ["main_dinner_main"],
        "forbidden_block_ids": ["main_karaoke_rounds", "main_pinata", "main_kids_obstacle"],
    },
    "holiday": {
        "label": "Holiday gathering",
        "ages": "all",
        "default_minutes": 240,
        "default_group_size": 16,
        "default_energy_target": "mid",
        "must_include_stages": ["welcome", "main", "intermission", "closer", "wind_down"],
        "required_block_ids": [],
        "forbidden_block_ids": ["main_pinata", "main_kids_obstacle"],
    },
    "reunion": {
        "label": "Reunion / friend-group catch-up",
        "ages": "adults_teens",
        "default_minutes": 180,
        "default_group_size": 10,
        "default_energy_target": "mid",
        "must_include_stages": ["welcome", "opener", "main", "wind_down"],
        "required_block_ids": [],
        "forbidden_block_ids": ["main_pinata", "main_kids_obstacle", "main_karaoke_rounds"],
    },
    "kids_party": {
        "label": "Kids party",
        "ages": "kids",
        "default_minutes": 120,
        "default_group_size": 12,
        "default_energy_target": "high",
        "must_include_stages": ["welcome", "opener", "main", "closer", "wind_down"],
        "required_block_ids": ["closer_cake_candles"],
        "forbidden_block_ids": ["main_karaoke_rounds", "main_dinner_main", "opener_never_have_i"],
    },
    "couples_night": {
        "label": "Couples night",
        "ages": "adults_teens",
        "default_minutes": 180,
        "default_group_size": 8,
        "default_energy_target": "low",
        "must_include_stages": ["welcome", "main", "wind_down"],
        "required_block_ids": [],
        "forbidden_block_ids": ["main_pinata", "main_kids_obstacle"],
    },
    "work_offsite": {
        "label": "Work offsite / team social",
        "ages": "adults_teens",
        "default_minutes": 180,
        "default_group_size": 12,
        "default_energy_target": "mid",
        "must_include_stages": ["welcome", "main", "wind_down"],
        "required_block_ids": [],
        "forbidden_block_ids": ["main_karaoke_rounds", "opener_never_have_i"],
    },
}


def blocks_for_occasion(occasion: str):
    return [b for b in BLOCKS if occasion in b["occasions"]]


def get_block(block_id: str):
    for b in BLOCKS:
        if b["id"] == block_id:
            return b
    return None


def all_occasion_keys():
    return list(OCCASION_TEMPLATES.keys())
